sudo: false
language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: dLv21dOT88rQ9nv9vvLIotEw893pghB5FVIO/s4EufrqXbaTDcAum8WCZCmqYlvX2/HgynJIhAf1WikBl8rVDpNNrnrEo0oHynCjZF4uvIVbljUIaN/rpXF7jsjMABJcKNpsc+OalL5Kk6S7gXGkBC9/HBTIxRVmnI50mzGoEEyn5VzdQFEFxxbLh7wyBk4AYJ9H9MNXrsl2tp50mW7ZKSdH1cdyYg8e/E1KrOAR7E4w4XMy2H1izWJ8XZ+qt3mvkaXV/m0N+YiY//ViFO8l2gAWIKBu04dN2RmPIQzWwJFJE7Nutz3H+ASfzOsxP6dM9vlYzZ/2JrHbfk0ssgD9RNjiix7LHsLbsSt1sQO166rfeLZK33PWmEyuIU17bM3hY8/9sSLNfwl31pXtwUydKn2utH/t/QoFN1Ajippi6RBmpzrcZ28ybjT+fmqsd6Rrig1WA3Vo3rGKbD3ayRfOc01E0PGeIuEnKnK7dDVWKEbUB7hMMdeHH9Tl3ZxzTkmIEfTHOEWBxGHAcCTL2t0F0yhrJshAyJ7qy2XZ1GsJyZW5aMe0bWPlVGG0RSLkV5gq9r1UhmmnkqMrfEbygnpsHYey/d5IoU9OYkqJQC90Qh47V3j6nYJDH9Mb9mPSQ5R7GsTH6L7YXM/zyLh+o3Q3C63oUipMmScjWvKwjxXOn2g=
  app: helloworldci
  on: master
notifications:
  slack:
    rooms:
      secure: 4N5BtOdHUmNpV2yhWG6IhDT7g0oFoIDPFqydlNukCydJVOCMWy+nOxsmaIBvFCPdqosDB23VWU+7yWQq/Z8tBsqzBma8r+jk/wLwwyuZiwGPczrl3v+WR7H8i7fJx5DyTSJ4BxUXmDMSd7yv9bw3JJbETxPy4NKTZoZ8UVXlWC0OppFjCnDJDXjuGdPVE0QTIBuVC6Y94yCLfAnq8mFWhcxEX5ISICT5HS4UImo/f67ibMx3+x0E0BmVNUrKJoCYcyZp5S+6tbC1AB/D6qQDvBz+gqc8iseWcbq6GbIAlfRczpQoOLvMry7vdeq0FLTlMJ544FnH8cw5w+uHsk4Nzq85xqH0CriKb5exZd2zS9cY9pag1EeDG17l9t5f95enU6qwuK0cqRZSyz6nRfwSE5aOM+ZKMnf47Do97C0QVepxH9HMJ+ONrfblGH7cW6SAYDllEesvY8zJ6+4uUkmHRc7+AYn0Vo/ZvtZncBB561AkCG5Sm1YQtL9fJwzZVzdZU56OQTgicampd3OU56NRktahxrkb8oYQRoiyBzJPLhgnn9pLF+QIFFmyodbqWk/cTSYfPgF+j6bSXNl8/9Z4PoDTzjmzsd5gCfiIgJTyT2wcNSeL0CkvasRYGaJ29m6HXaEkV3nnH4W6vHP9Kik7/cRFlwGXM5FVnPjjAAqeRT0=
